title: Desi Minds
description: Culturally Sensitive Mental Health Support for Indians Living Abroad
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
header_pages:
  - index.md
  - about.md
